name: backend deployment to azure 🚀🚀

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

env:
  AZURE_WEBAPP_NAME: api-anzen
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"
  DOTNET_VERSION: "6.0.x"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "${{env.DOTNET_VERSION}}"

      - name: Restore
        run: dotnet restore ./backend/backend.sln

      - name: Build
        run: dotnet build ./backend/backend.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./backend/backend.sln --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'

      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
