name: flutter app build 🚀🚀

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

env:
  FLUTTER_VERSION: "3.10.3"
  FLUTTER_CHANNEL: "stable"

jobs:
  build_android:
    name: Android APK Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "${{env.FLUTTER_VERSION}}"
          channel: "${{env.FLUTTER_CHANNEL}}"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build apk
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: /frontend/build/app/outputs/flutter-apk/app-release.apk

  build_ios:
    name: IOS IPA Build
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "${{env.FLUTTER_VERSION}}"
          channel: "${{env.FLUTTER_CHANNEL}}"
      - run: flutter pub get
      - run: flutter clean
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: /frontend/build/ios/iphoneos/app.ipa
