name: flutter app build 🚀🚀

on:
  push:
    branches:
      - main
    paths:
      - "./frontend/**"

env:
  FLUTTER_VERSION: "3.10.3"
  FLUTTER_CHANNEL: "stable"

jobs:
  build_android:
    name: Android APK Build
    uses: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "${{env.FLUTTER_VERSION}}"
          channel: "${{env.FLUTTER_CHANNEL}}"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build apk
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk

  build_ios:
    name: IOS IPA Build
    uses: macos-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "${{env.FLUTTER_VERSION}}"
          channel: "${{env.FLUTTER_CHANNEL}}"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build ios --release --no-codesign
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/ios/iphoneos/app.ipa
